CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "Groups" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(5) NOT NULL,
        CONSTRAINT "PK_Groups" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" character varying(150) NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "PasswordHash" text NOT NULL,
        "PhotoUrl" character varying(500),
        "IsAdmin" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "Teams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "FifaCode" character varying(5) NOT NULL,
        "FlagUrl" character varying(500),
        "GroupId" integer,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Teams_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "PushSubscriptions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Endpoint" character varying(1000) NOT NULL,
        "P256dh" character varying(500) NOT NULL,
        "Auth" character varying(100) NOT NULL,
        "DeviceInfo" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_PushSubscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PushSubscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "Matches" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HomeTeamId" integer,
        "AwayTeamId" integer,
        "GroupId" integer,
        "Phase" integer NOT NULL,
        "Status" integer NOT NULL,
        "MatchDate" timestamp with time zone NOT NULL,
        "HomeScore" integer,
        "AwayScore" integer,
        "ExternalId" character varying(50),
        "Venue" character varying(200),
        "MatchLabel" character varying(200),
        "Matchday" integer NOT NULL,
        CONSTRAINT "PK_Matches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Matches_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Matches_Teams_AwayTeamId" FOREIGN KEY ("AwayTeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Matches_Teams_HomeTeamId" FOREIGN KEY ("HomeTeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE TABLE "Predictions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "MatchId" integer NOT NULL,
        "HomeScore" integer NOT NULL,
        "AwayScore" integer NOT NULL,
        "Points" integer NOT NULL DEFAULT 0,
        "IsProcessed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Predictions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Predictions_Matches_MatchId" FOREIGN KEY ("MatchId") REFERENCES "Matches" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Predictions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Groups_Name" ON "Groups" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE INDEX "IX_Matches_AwayTeamId" ON "Matches" ("AwayTeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE INDEX "IX_Matches_GroupId" ON "Matches" ("GroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE INDEX "IX_Matches_HomeTeamId" ON "Matches" ("HomeTeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE INDEX "IX_Predictions_MatchId" ON "Predictions" ("MatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Predictions_UserId_MatchId" ON "Predictions" ("UserId", "MatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PushSubscriptions_UserId_Endpoint" ON "PushSubscriptions" ("UserId", "Endpoint");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Teams_FifaCode" ON "Teams" ("FifaCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE INDEX "IX_Teams_GroupId" ON "Teams" ("GroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_PhoneNumber" ON "Users" ("PhoneNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260601220036_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260601220036_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

